set -s default-terminal "tmux-256color"
set -s escape-time 0
bind-key R source-file ~/.tmux.conf \; \
       display-message "source-file done"
bind-key -T prefix / copy-mode \; \
        command-prompt -p "(search up)" "send -X search-backward \"%%%\""
run-shell "$HOME/.tmux/tmux-resurrect/resurrect.tmux"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
set-window-option -g mode-keys vi
set-option -g history-limit 50000

# Use Shift-arrow keys without prefix key to switch panes
bind -n S-Left select-pane -L
bind -n S-Right select-pane -R
bind -n S-Up select-pane -U
bind -n S-Down select-pane -D

# Use Alt-arrow keys to switch windows
bind -n M-Left  previous-window
bind -n M-Right next-window

# Use Alt-num keys to switch windows
set -g base-index 1
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 0

# Use Alt-shift num keys to swap windows
bind-key -n M-S-Left swap-window -t -1\; select-window -t -1
bind-key -n M-S-Right swap-window -t +1\; select-window -t +1

# Enable applications within tmux to set the clipboard.
# See <https://github.com/tmux/tmux/wiki/Clipboard>.
set -s set-clipboard on

# needed for iterm2 shell integration
set -gq allow-passthrough on

# needed for mosh OSC52
# See <https://gist.github.com/yudai/95b20e3da66df1b066531997f982b57b>
set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"

set -g mouse on
# https://github.com/tmux/tmux/wiki/Recipes#send-up-and-down-keys-for-the-mouse-wheel
bind -n WheelUpPane {
    if -F '#{||:#{pane_in_mode},#{mouse_any_flag}}' {
        send -M
    } {
        if -F '#{alternate_on}' { send-keys -N 3 Up } { copy-mode -e }
    }
}
bind -n WheelDownPane {
    if -F '#{||:#{pane_in_mode},#{mouse_any_flag}}' {
        send -M
    } {
        if -F '#{alternate_on}' { send-keys -N 3 Down }
    }
}
