# subcommands

# general options
complete -c chezmoi -l color --no-files -a "auto yes no" --description "colorize diffs (default auto)"
complete -c chezmoi -s c -l config --description "config file (default /home/jesse/.config/chezmoi/chezmoi.toml)"
complete -c chezmoi -l cpu-profile --description "write CPU profile"
complete -c chezmoi -l debug --description "write debug logs"
complete -c chezmoi -s D -l destination --description "destination directory (default $HOME)"
complete -c chezmoi -s n -l dry-run --description "dry run"
complete -c chezmoi -l force --description "force"
complete -c chezmoi -s h -l help --description "help for chezmoi"
complete -c chezmoi -s k -l keep-going --description "keep going as far as possible after an error"
complete -c chezmoi -l no-pager --description "do not use the pager"
complete -c chezmoi -l no-tty --description "don't attempt to get a TTY for reading passwords"
complete -c chezmoi -s o -l output --description "output file"
complete -c chezmoi -l remove --description "remove targets"
complete -c chezmoi -s S -l source --description "source directory (default $HOME/.local/share/chezmoi)"
complete -c chezmoi -l source-path --description "specify targets by source path"
complete -c chezmoi -l use-builtin-git --no-files -a "auto yes no" --description "use builtin git (default auto)"
complete -c chezmoi -s v -l verbose --description "verbose"
complete -c chezmoi -l version --description "version for chezmoi"
