[general]
import = [
    "themes/solarized_light.toml",
]

[keyboard]
bindings = [
    { "key" = "F11", "action" = "ToggleFullscreen" },
]

[font]
normal = { family = "Monaco", style = "Regular" }
size = 16

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Fullscreen"
