[general]
import = [
    "themes/solarized_light.toml",
]

[keyboard]
bindings = [
    { "key" = "F11", "action" = "ToggleFullscreen" },
]

[window]
decorations = "None"
option_as_alt = "OnlyLeft"

[font]
normal = { family = "Monaco", style = "Regular" }
size = 16
