[general]
import = [
    "themes/solarized_light.toml",
]

[window]
option_as_alt = "OnlyLeft"

[font]
# TODO: separate configuration per OS
normal = { family = "Monaco", style = "Regular" }
size = 16
