[general]
import = [
    "themes/solarized_light.toml",
]

[keyboard]
bindings = [
    { "key" = "F11", "action" = "ToggleFullscreen" },
]

[font]
size = 16

[window]
decorations = "None"
startup_mode = "Maximized"
